package ArjaE.FindInArray.bug12.Repaired;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class FindInArrayTest {

	/*
	 * Test case assumes findLast() returns invalid value
	 */
	@Test
	void test0() {
		fail("The function find_first() is not testable for this case");
	}

	/*
	 * Test case assumes findLast() returns invalid value
	 */
	@Test
	void test1() {
		fail("The function find_first() is not testable for this case");
	}

}
